language: bash
os:
  - osx
env:
  - FLUTTER_CHANNEL="stable"
sudo: false
before_script:
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH=$PATH:$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin
  - cd -
  - flutter doctor
script:
  - set -e # abort CI if an error happens
  - flutter test --covergae

  # export coverage
  - bash <(curl -s https://codecov.io/bash);
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.pub-cache