name: horizontal_calendar
description: Easy to use, highly customizable horizontal calendar.
version: 1.0.0
author: SoluteLabs <opensource@solutelabs.com>
homepage: https://github.com/solutelabs/horizontal_calendar

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter